services:
  # mongo:
  #   image: mongo
  #   container_name: canado_mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example    

  app:
    image: 19122002/canado:latest
    container_name: canado
    ports:
      - 8888:8888
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

